### PR TITLE
Add Ruby 2.4 to test matrix.

### PR DESCRIPTION
**Pull request by connorshea**
Happy holidays!

### CODE REVIEW

**Comment by connorshea** [comment]
Until rails/rails@47c4924 is released in Rails 4.2.8, Ruby 2.4 won't work with it.

**Comment by k0kubun** [comment]
We can drop json dependency without waiting ActiveSupport 4.2.8. rack-lineprof has rack ~> 1.5 dependency and it locks Rails to 4.x. lineprof gem is useless and it's okay to remove that from gemspec :)

**Comment by connorshea** [comment]
@k0kubun for some reason I was thinking this used rails for tests, whoops :D Let's see if the tests pass now.

**Comment by connorshea** [comment]
@k0kubun https://github.com/k0kubun/hamlit/blob/master/hamlit.gemspec#L34

rails is used as a development dependency, looks like.

**Comment by k0kubun** [comment]
Yes it's intentional. We can drop json dependency without waiting ActiveSupport 4.2.8 *by using Rails 5*. 

And we can avoid the last CI failure like this https://github.com/k0kubun/rack-user_agent/commit/b2ca61332e19f6972465f92a50eb2b84c4471f29.

**Comment by connorshea** [comment]
@k0kubun in that case we'd either have to drop Ruby 2.1 from the test matrix or use separate gemfiles, which do you prefer?

**Comment by k0kubun** [comment]
There is no need to drop Ruby 2.1 if you use https://github.com/k0kubun/rack-user_agent/commit/b2ca61332e19f6972465f92a50eb2b84c4471f29. Even Ruby 2.0.0 is supported in that repository https://github.com/k0kubun/rack-user_agent/blob/b2ca61332e19f6972465f92a50eb2b84c4471f29/.travis.yml (though it should be removed now).

**Comment by connorshea** [comment]
@k0kubun but Rails 5 also requires Ruby 2.2.2 or greater, so Ruby 2.1 still wouldn't work. Unless I'm misunderstanding?

**Comment by k0kubun** [comment]
If you specify `rack < 2`, it also means that you specify Rails 4 and it doesn't require Ruby >= 2.2.2.

**Comment by connorshea** [comment]
@k0kubun oh I see, okay, that should work. It seems like it'd be simpler to use separate gemfiles though, no?

**Comment by k0kubun** [comment]
I agree that it's simpler but how do you avoid duplication of other gems like minitest-line, pry-byebug in Gemfiles? They are not depended by any code in this repository but I often use it and add it to Gemfile. And writing the same gem list to separated files is lengthy.

Anyway, to review, please modify Gemfile as you like.

**Comment by k0kubun** [comment]
In addition, separating Gemfile is not so normal and it should have some comment describing the reason. I prefer https://github.com/k0kubun/rack-user_agent/commit/b2ca61332e19f6972465f92a50eb2b84c4471f29 because the code is descriptive about the reason and doesn't need a comment. And it's easy to follow the dependency changes.

**Comment by connorshea** [comment]
Rails 4.2.8 should be coming out soon, so I'll just wait for that.

As for the separate gemfiles, that's not too uncommon, [carrierwave](https://github.com/carrierwaveuploader/carrierwave/tree/master/gemfiles) and [devise](https://github.com/plataformatec/devise/tree/master/gemfiles) do it, for example.

**Comment by k0kubun** [comment]
I do [that](https://github.com/k0kubun/activerecord-precount/tree/v0.6.2/ci) if it's really necessary, i.e. testing multiple Rails in one repository. Hamlit is not Rails plugin and I've thought there's no need to test multiple Rails versions. But if your intention is to test against both ActionView 4.2 and 5.0, it should be separated.

> Rails 4.2.8 should be coming out soon, so I'll just wait for that.

You mean you want to use Rails 4 forever? Because https://github.com/kainosnoema/rack-lineprof/pull/4 is merged, Rails won't be locked to 5 if rack-lineprof > 0.0.3 is released.

**Comment by k0kubun** [comment]
Taking over your patch. Thank you for your contribution!

**Pull request merged**
